telegram:
  bot:
    token: ${BOT_TOKEN}
    username: ${BOT_USERNAME}
    admin-chat-id: ${ADMIN_CHAT_ID}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/osbb_bot
    username: postgres
    password: postgres
  jpa:
    show-sql: true

logging:
  level:
    ua.horuktaras: DEBUG
